name: Ayden Marshall
description: This is my mind dump.
meta_description: "Ayden Marshall Blog"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "aydenmarshall.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Ayden Marshall"

# Disqus config
disqus-shortname: ""
